# Generated by Django 2.0.7 on 2018-07-04 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180704_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='created_date',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='userpost',
            old_name='title',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='userpost',
            name='to_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='approval',
            field=models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('NOT APPROVED', 'NOT APPROVED')], max_length=100),
        ),
    ]
