# Generated by Django 2.0.7 on 2018-07-04 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180704_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
