# Generated by Django 2.0.7 on 2018-07-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20180704_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='userposts',
        ),
    ]
